# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby_ucp}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sergio Freire"]
  s.date = %q{2011-10-21}
  s.description = %q{Ruby library implementation of EMI/UCP protocol v4.6 for SMS}
  s.email = %q{sergio.freire@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README",
    "Rakefile",
    "Rakefile.orig",
    "VERSION",
    "lib/performance/stresser.rb",
    "lib/ruby_ucp.rb",
    "lib/samples/main.rb",
    "lib/ucp/base.rb",
    "lib/ucp/pdu/base.rb",
    "lib/ucp/pdu/ucp01.rb",
    "lib/ucp/pdu/ucp01_operation.rb",
    "lib/ucp/pdu/ucp01_result.rb",
    "lib/ucp/pdu/ucp30.rb",
    "lib/ucp/pdu/ucp30_operation.rb",
    "lib/ucp/pdu/ucp30_result.rb",
    "lib/ucp/pdu/ucp31.rb",
    "lib/ucp/pdu/ucp31_operation.rb",
    "lib/ucp/pdu/ucp31_result.rb",
    "lib/ucp/pdu/ucp51_operation.rb",
    "lib/ucp/pdu/ucp51_result.rb",
    "lib/ucp/pdu/ucp52_operation.rb",
    "lib/ucp/pdu/ucp52_result.rb",
    "lib/ucp/pdu/ucp53_operation.rb",
    "lib/ucp/pdu/ucp53_result.rb",
    "lib/ucp/pdu/ucp54_operation.rb",
    "lib/ucp/pdu/ucp54_result.rb",
    "lib/ucp/pdu/ucp55_operation.rb",
    "lib/ucp/pdu/ucp55_result.rb",
    "lib/ucp/pdu/ucp56_operation.rb",
    "lib/ucp/pdu/ucp56_result.rb",
    "lib/ucp/pdu/ucp57_operation.rb",
    "lib/ucp/pdu/ucp57_result.rb",
    "lib/ucp/pdu/ucp58_operation.rb",
    "lib/ucp/pdu/ucp58_result.rb",
    "lib/ucp/pdu/ucp5x.rb",
    "lib/ucp/pdu/ucp60.rb",
    "lib/ucp/pdu/ucp60_operation.rb",
    "lib/ucp/pdu/ucp60_result.rb",
    "lib/ucp/pdu/ucp61.rb",
    "lib/ucp/pdu/ucp61_operation.rb",
    "lib/ucp/pdu/ucp61_result.rb",
    "lib/ucp/pdu/ucp_operation.rb",
    "lib/ucp/pdu/ucp_result.rb",
    "lib/ucp/pdu/ucpmessage.rb",
    "lib/ucp/util/auth_request.rb",
    "lib/ucp/util/base.rb",
    "lib/ucp/util/gsm_packed_msg.rb",
    "lib/ucp/util/packed_msg.rb",
    "lib/ucp/util/sms_request.rb",
    "lib/ucp/util/ucp.rb",
    "lib/ucp/util/ucp_client.rb",
    "lib/ucp/util/ucp_server.rb",
    "lib/ucp/util/ucs2_packed_msg.rb"
  ]
  s.homepage = %q{https://github.com/bitcoder/ruby_ucp}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{EMI/UCP protocol library}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

